name: ChatClearer
author: Dog2puppy
api: [1.0.0]
version: 1.0
main: Dog2puppy\Main
# Note that after SRC Directory, include all sub folder directories to Main but do not include .php extension in plugin.yml and This main PluginPlugin IS JUST AN EXAMPLE

# Commands
commands:
clear: 
  description: Clear your chat window!
  usage: /clear

# Permissions
permissions:
